version: '3.8'
services:
  webdc:
    build: 
      context: ./fastapi
      dockerfile: ../Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3